# Generated by Django 3.1.6 on 2021-02-09 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('link_1', models.URLField(verbose_name='Ссылка на фото')),
                ('link_2', models.URLField(blank=True, verbose_name='Ссылка на фото')),
                ('link_3', models.URLField(blank=True, verbose_name='Ссылка на фото')),
            ],
        ),
    ]
